export { default as About } from "./about"
export { default as Contact } from "./contact"
export { default as Gallery } from "./gallery"
export { default as Header } from "./header"
export { default as Navbar } from "./navbar"
export { default as Services } from "./services"
